version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin